### PR TITLE
Update fulcrum audits

### PR DESCRIPTION
**Pull request by sneg55**

### CODE REVIEW

**Comment by tlip** [comment]
Hey @sneg55, thanks for your contribution 🙏. 

It's _really_ close to approval IMO, but first a few questions:

1) Would it be possible to add a (very brief) high-level summary of the nature of each audit in their `"notes"` field that gives a bit of context on the scope of the audits? I know that not every audit included thus far in the repo has this field populated (yet), but we _do_ intend on making sure they will be in the near future.... and I 100% believe that this particular information is probably more valuable if it comes from the community rather than from us.
2) It looks like one is actual a formal verification. What do you think about calling out that fact in the notes field?
3) Can you verify the length of the audits? You list them both at 2 weeks but I don't see that on the reports?

**Comment by sneg55** [comment]
1. Added. 

2. Title on both audits says it is  "Audit", I guess we can trust that.  
 
image

image

3. Certik did confirm 2 weeks' length with us. How you want me to prove it? It wasn't mentioned anywhere in the original audit report.

**Comment by KyleJKistner** [comment]
We haven't had any formal verification yet. Both audits were manual. CertiK does do formal verification and I see that expressed in one of the watermarks on the top of the report ("Formal Verification Platform") but a reading of the audits does confirm that these were done manually.

**Comment by jordanlyall** [comment]
We're not trying to be difficult here. But calling it a "full protocol audit" isn't fair to the other protocols. It literally states on the second page "...does not constitute a full audit"

image

**Comment by tomcbean** [comment]
These aren't full audits of the entire protocol, just parts of it. We have full audits scheduled for the near future, for v2 of our protocol, prior to us relaunching.

**Comment by tomcbean** [comment]
@jordanlyall One audit was for the flash loan code, and the other was an audit of changes to secure the protocol prior to allowing traders and borrowers to close their positions. It also included an audit of the Chainlink integration. Do you need more info than that?

**Comment by sneg55** [comment]
@flamingYawn  updated notes

**Review by tlip — APPROVED** [review]

**Pull request merged**
